---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - servicenow.itsm
  vars_files:
    - snow_vars.yml


  # Hey Ya!

  tasks:

  - name: Create a ServiceNow Change Request
    servicenow.itsm.change_request:
      instance: 
        username: "{{ sn_username }}"
        password: "{{ sn_password }}"
        host: "https://{{ sn_instance }}.service-now.com"
      state: "{{ sn_state }}" 
      assignment_group: "{{ sn_assignment_group }}"
      number: "{{ sn_number }}"
