---
- name: SNOW - Create an incident
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
  vars_files:
    - snow_vars.yml


  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        instance: 
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
        state: new
        caller: "Iggy Pop"
        short_description: "User created a new incident using Ansible Automation Platform"
        description: "User Iggy Pop successfully created a new incident!"
        impact: low
        urgency: low
      register: new_incident

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"

