---
- name: SNOW Create an incident - AAP
  hosts: localhost
  connection: local

  vars: 
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks:

    - name: Dump out the env
      ansible.builtin.debug:
        msg: "{{ sn_username }} is our user."

    # - name: Create incident
    #   servicenow.itsm.incident:
    #     state: new
    #     caller: "Chris.Norville"
    #     short_description: "User Scooter created a new incident using Ansible"
    #     description: "User Scooter successfully created a new incident! Something is broken! Fix it!"
    #     impact: low
    #     urgency: low
    #   register: new_incident

    # - set_fact:
    #     incident_number_cached: "{{ new_incident.record.number }}"
    #     cacheable: true

    # - ansible.builtin.debug:
    #     msg: "A new incident has been created: {{ new_incident.record.number }}"