---
- name: SNOW Create an incident - AAP - Basic Functionality 
  hosts: localhost
  connection: local
  gather_facts: No
  environment:

  vars:
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ sn_username }}"
        short_description: "Pod Replica issues for application in the Norville OCP Cluster"
        description: "The {{ ocp_deployment_name }} deployment in the {{ ocp_namespace }} namespace on the OCP Cluster has been scaled to 0"
        impact: low
        urgency: low
      register: new_incident
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - ansible.builtin.debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"