---
- name: SNOW - Create an incident - AAP
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm

  tasks:

    - name: Create incident
      incident:
        instance: 
          host: "https://{{ sn_instance }}.service-now.com"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"

        state: new
        caller: "{{ sn_username }}"
        short_description: "User {{ sn_username }} created a new incident using Ansible for Kyndryl"
        description: "User {{ sn_username }} successfully created a new incident! Something is broken! Fix it!"
        impact: low
        urgency: low
      register: new_incident

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"

