---
- name: SNOW - Create an incident
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
  vars_files:
    - snow_vars.yml

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        instance: 
          host: "https://{{ sn_instance }}.service-now.com"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
        state: new
        caller: "{{ sn_username }}"
        short_description: "User {{ sn_username }} created a new incident using Ansible for Nordstrom"
        description: "User {{ sn_username }} successfully created a new incident!"
        impact: low
        urgency: low
      register: new_incident

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"

