---
- name: SNOW Create an incident - AAP - Basic Functionality 
  hosts: localhost
  connection: local
  gather_facts: No
  environment:

  vars:
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ sn_username }}"
        short_description: "Testing AAP to ServiceNow Basic Functionality"
        description: "Testing the connections and basic functionality from AAP to ServiceNow, Opening a dummy Incident"
        impact: low
        urgency: low
      register: new_incident
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - ansible.builtin.debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"