---
- name: SNOW Create an incident - AAP
  hosts: zos
  gather_facts: No
  
  vars:
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ sn_username }}"
        short_description: "User {{ sn_username }} created a new incident using Ansible"
        description: "User {{ sn_username }} successfully created a new incident! Something is broken! Fix it!"
        impact: low
        urgency: low
      register: new_incident
      delegate_to: localhost

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - ansible.builtin.debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"

    - name: Ping the mainframe to see if we can work with it, update the ticket
      zos_ping: 
      register: ping_result

    - name: Display the ping result
      debug: 
        msg: "{{ ping_result.ping }}"

    - name: Update the SNOW ticket before running the JCL
      incident:
        state: in_progress
        caller: "{{ sn_username }}"
        number: "{{ incident_number_cached }}"
        other:
          work_notes: "We are looking at the problem!"